---

- hosts: bhyve_hosts
  gather_facts: no

  roles:
    # This role doesn't currently do anything useful. Keeping it around for now
    # because it contains some interesting work for list handling in Ansible;
    # might be useful at a later time.
#    - { role: bhyve_init, tags: bhyve }
    - { role: bhyve_switch_prep, tags: "bhyve,switch"}
    - { role: bhyve_host_prep, tags: bhyve }

- hosts: bhyve_guests
  gather_facts: no

  # This needs to be run serially. When the guest zvol is cloned, it retains the
  # guid of the source pool. ZFS only allows a single imported instance of a
  # given guid, so all guest clones after the first will fail. zpool reguid can
  # be used to change a zpool, but doesn't seem practical right now.
  serial: 1

  roles:
    - { role: vm_prep, tags: vm }

- hosts: os_freebsd

  roles:
    - { role: freebsd_config, tags: freebsd }
    - { role: pf, tags: pf }
    - { role: user_management, tags: users }

- hosts: birdies

  roles:
    - { role: bird, tags: bird }

# vim: set ts=2 sw=2 tw=80 ft=yaml :
